#!/usr/bin/env bash
set -e

API_PORT=${API_PORT:-8001}

echo "API: http://127.0.0.1:${API_PORT}"

uv run uvicorn \
    app.__main__:crate_app \
    --factory \
    --host 127.0.0.1 \
    --port ${API_PORT} \
    --reload \
    --reload-dir app \
    --reload-dir quantflow
