#!/usr/bin/env bash
set -e

OBSERVABLE_PORT=${OBSERVABLE_PORT:-3001}
DOCS_PORT=${DOCS_PORT:-8000}
API_PORT=${API_PORT:-8001}
FRONTEND_ORIGIN=${FRONTEND_ORIGIN:-http://127.0.0.1:${OBSERVABLE_PORT}}
QUANTFLOW_API_ORIGIN=${QUANTFLOW_API_ORIGIN:-http://127.0.0.1:${API_PORT}}

npm --prefix app/frontend exec concurrently -- \
    --kill-others \
    --names docs,examples,api \
    --prefix "[{name}]" \
    "DOCS_PORT=${DOCS_PORT} bash ./dev/mkdocs-serve" \
    "OBSERVABLE_PORT=${OBSERVABLE_PORT} QUANTFLOW_API_ORIGIN=${QUANTFLOW_API_ORIGIN} bash ./dev/frontend-serve" \
    "API_PORT=${API_PORT} QUANTFLOW_CORS_ORIGINS=${FRONTEND_ORIGIN} bash ./dev/api-serve"
