#!/usr/bin/env bash
set -e

ISORT_ARGS="-c"
BLACK_ARG="--check"
RUFF_ARG=""
TAPLO_ARG="format --check"
PACKAGES="quantflow quantflow_tests docs/examples"

if [ "$1" = "fix" ] ; then
    ISORT_ARGS=""
    BLACK_ARG=""
    RUFF_ARG="--fix"
    TAPLO_ARG="format"
fi

taplo ${TAPLO_ARG}
echo isort
uv run isort ${PACKAGES} ${ISORT_ARGS}
echo black
uv run black ${PACKAGES} ${BLACK_ARG}
echo ruff
uv run ruff check ${PACKAGES} ${RUFF_ARG}
echo mypy
uv run mypy ${PACKAGES}
