#!/usr/bin/env bash
set -e

OBSERVABLE_PORT=${OBSERVABLE_PORT:-3001}
DOCS_PORT=${DOCS_PORT:-8000}
API_PORT=${API_PORT:-8001}

echo "Documentation: http://127.0.0.1:${DOCS_PORT}"
echo "Examples: http://127.0.0.1:${OBSERVABLE_PORT}"
echo "API: http://127.0.0.1:${API_PORT}"
