#!/usr/bin/env bash
set -e

QUANTFLOW_API_PORT=${QUANTFLOW_API_PORT:-8001}

echo "API: http://127.0.0.1:${QUANTFLOW_API_PORT}"

uv run uvicorn \
    app.__main__:crate_app \
    --factory \
    --host 127.0.0.1 \
    --port ${QUANTFLOW_API_PORT} \
    --reload \
    --reload-dir app \
    --reload-dir quantflow
