# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Quantflow library
author: Quantmind Team
copyright: "2024"
logo: assets/quantflow-light.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  #execute_notebooks: "off"
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - reference/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/quantmind/quantflow  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: assets/quantflow-logo.png
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  analytics:
    google_analytics_id: G-XBNNWQ560T

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath

sphinx:
  recursive_update: true
  config:
    html_js_files:
    # required by plotly charts
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_options: {
        "async": "async",
    }
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx_autodoc_typehints"
    - "sphinx.ext.autosummary"
    - "sphinx.ext.intersphinx"
    - "sphinx_autosummary_accessors"
    - "sphinx_copybutton"
    - "autodocsumm"
